export { ReactComponent as LoaderComp } from './loader.svg'
export { ReactComponent as AddImgIconComp } from './add-img-icon.svg'
export { ReactComponent as PlusIconComp } from './plus-icon.svg'
export { ReactComponent as SearchIconComp } from './search-icon.svg'
export { ReactComponent as StarsIconComp } from './stars-icon.svg'

export { default as jacqueFrescoTokenIcon } from './jacque-fresco-token.png'
export { default as blakMonkeTokenIcon } from './blak-monke-token.png'
export { default as bobbyTokenIcon } from './bobby-token.png'
export { default as miniTokenIcon } from './mini-token.png'
export { default as swappyTokenIcon } from './swappy-token.png'
